[toolchain]
anchor_version = "0.30.1"

[features]
seeds = false
skip-lint = false

[programs.devnet]
oracle_simple = "D4cJpMwYznwqVC1dT4ARA5egbAwaxqjbBgsAqWyetymC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./target/deploy/new_program-keypair.json"

[scripts]
test = "../node_modules/.bin/nx run anchor:jest"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "127.0.0.1"
ledger = ".anchor/test-ledger"
rpc_port = 8899
